import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { Module } from '@nestjs/common';
import {
  applyPatch,
  namesOf,
  planModule,
  refusals,
  writeModule,
  type GeneratedModule,
  type ModuleRequest,
} from '../src/platform/generator';
import {
  assembleModules,
  discoverManifests,
  ModuleContractError,
  type ModuleManifest,
} from '../src/platform/modules';
import { checkConformance, readSources } from '../src/platform/conformance';
import { classifiedModels, grantsByModel } from '../src/platform/tenancy/company-owned';

/**
 * The generator, and the claim that earns it its place: what it produces is already correct.
 *
 * "Correct" is not a matter of opinion here, which is the point. The build already refuses a
 * module that will not assemble (`assembleModules`) and one that breaks the boundary rules
 * (`checkConformance`), and both are pure functions over declarations and text. So the test
 * for a generated module is to hand what the generator *would write* to the same two
 * functions the build runs, before anything touches a disk.
 *
 * That is why `planModule` is pure. The alternative — generating into the working tree,
 * running the checks as subprocesses and cleaning up — would be slower, would need a git
 * status nobody was in the middle of, and would leave eleven files and three patched central
 * files behind on the first failure.
 *
 * The one claim these cannot make is that the generated *TypeScript compiles*, because that
 * needs a compiler over the whole program. What makes that claim is products: it was
 * generated by this generator, it is in the tree, and the build compiles it like everything
 * else. A generator whose output did not compile would fail `npm run build`, loudly, on the
 * module it produced.
 */

@Module({})
class StubNestModule {}

/** The plan's declaration as a manifest — the same value with the class it names filled in. */
function asManifest(plan: GeneratedModule): ModuleManifest {
  return { ...plan.declaration, nestModule: StubNestModule };
}

function request(overrides: Partial<ModuleRequest> = {}): ModuleRequest {
  return {
    name: 'widgets',
    tier: 'core',
    dependsOn: [],
    // Fixed rather than taken from the clock, so what these assert does not depend on when
    // they run. The CLI passes the real time; nothing else should.
    stamp: '20260901120000',
    ...overrides,
  };
}

describe('the module generator', () => {
  describe('what it writes', () => {
    it('produces a backend module, a frontend module, a contract, a migration and tests', () => {
      const plan = planModule(request());

      expect(plan.files.map((file) => file.path)).toEqual([
        'backend/src/modules/widgets/widgets.manifest.ts',
        'backend/src/modules/widgets/widgets.module.ts',
        'backend/src/modules/widgets/widgets.controller.ts',
        'backend/src/modules/widgets/widgets.service.ts',
        'backend/src/modules/widgets/schemas.ts',
        'backend/src/modules/widgets/index.ts',
        'backend/prisma/migrations/20260901120000_widgets/migration.sql',
        'backend/test/widgets.spec.ts',
        'packages/src/modules/widgets/contract.ts',
        'application/src/modules/widgets/manifest.ts',
        'application/src/modules/widgets/pages/WidgetsPage.tsx',
        'application/src/modules/widgets/pages/WidgetsPage.test.tsx',
      ]);

      // The frontend mirrors the backend: same module name, same place in its own workspace,
      // a manifest declaring which component renders which path.
      expect(plan.files.find((file) => file.path.endsWith('application/src/modules/widgets/manifest.ts'))?.text)
        .toContain("path: '/widgets'");
    });

    it('declares a manifest, a public surface and navigation without anything central being edited', () => {
      const plan = planModule(request({ name: 'field-service', tier: 'custom' }));

      expect(plan.declaration).toMatchObject({
        name: 'field-service',
        tier: 'custom',
        routes: ['api/field-service'],
        models: ['FieldService'],
        permissions: ['field-service:field-service:read', 'field-service:field-service:write'],
        migrations: ['20260901120000_field_service'],
      });
      expect(plan.declaration.navigation).toEqual([
        {
          label: 'Field service',
          path: '/field-service',
          order: 50,
          permission: 'field-service:field-service:read',
        },
      ]);

      // A module with nothing to offer says so, which is a real answer rather than an
      // omission — and it is what everything else in the directory is measured against.
      const surface = plan.files.find((file) => file.path.endsWith('field-service/index.ts'));
      expect(surface?.text).toContain('export {}');
    });

    it('derives every name from the one the person typed, and takes a correction for the record', () => {
      // The five conventions a hand-written module gets right on a good day: the Nest class
      // prefix, the constant prefix, the model, the delegate and the table.
      expect(namesOf('products')).toMatchObject({
        pascal: 'Products',
        constant: 'PRODUCTS',
        record: 'Product',
        recordConstant: 'PRODUCT',
        delegate: 'product',
        table: 'products',
      });

      // English is not something a rule gets right, so the singulariser is overridable.
      expect(namesOf('parties').record).toBe('Party');
      expect(namesOf('identity').record).toBe('Identity');
      expect(namesOf('stock', 'StockMovement')).toMatchObject({
        record: 'StockMovement',
        recordConstant: 'STOCK_MOVEMENT',
        delegate: 'stockMovement',
      });
    });
  });

  /**
   * The three edits a directory cannot express, and the reason the generator does them.
   *
   * Each is a file somebody would otherwise have to remember, and forgetting each one fails
   * somewhere different and unhelpful: a missing table at the first query, a refused boot, a
   * type that will not resolve in the other workspace.
   */
  describe('the central files it patches', () => {
    it('classifies the new table inside the tenancy table rather than after it', () => {
      const plan = planModule(request());
      const patch = plan.patches.find((candidate) => candidate.path.endsWith('company-owned.ts'));
      const before = readFileSync(
        resolve(__dirname, '../src/platform/tenancy/company-owned.ts'),
        'utf8',
      );

      const after = applyPatch(before, patch!);
      const table = after.slice(after.indexOf('const CLASSIFICATION'), after.indexOf('\n};'));

      expect(table).toContain("Widget: { kind: 'company-owned' }");
      // Company-owned rather than unscoped, deliberately: a generated guess of 'unscoped'
      // would be a generated leak, and the boot refuses an unclassified table anyway.
      expect(after).toContain('export function tenancyOf');
    });

    it('adds the model to the schema and the contract to the shared barrel', () => {
      const plan = planModule(request());
      const schema = plan.patches.find((candidate) => candidate.path.endsWith('schema.prisma'));
      const barrel = plan.patches.find((candidate) => candidate.path.endsWith('packages/src/index.ts'));

      expect(applyPatch('// schema\n', schema!)).toContain('model Widget {');
      expect(applyPatch('// schema\n', schema!)).toContain('@@map("widgets")');
      expect(applyPatch("export * from './http/error.js';\n", barrel!)).toContain(
        "export * from './modules/widgets/contract.js';",
      );
    });

    it('refuses to guess when a patch no longer knows where it goes', () => {
      const plan = planModule(request());
      const patch = plan.patches.find((candidate) => candidate.path.endsWith('company-owned.ts'));

      // Writing the classification somewhere arbitrary would produce a file that does not
      // compile, which is recoverable — but the same trick in schema.prisma would produce one
      // that does.
      expect(() => applyPatch('nothing like the file it expected', patch!)).toThrow(
        /anchors to is not there/i,
      );
    });
  });

  describe('what it refuses, before writing anything', () => {
    const existing = discoverManifests();

    function refuse(overrides: Partial<ModuleRequest>): string {
      const asked = request(overrides);
      return refusals(asked, namesOf(asked.name, asked.record), existing).join('\n');
    }

    it('refuses a name a module already has', () => {
      expect(refuse({ name: 'parties' })).toMatch(/already exists/i);
      // And nothing is wrong with the same request under a different name.
      expect(refuse({ name: 'widgets' })).toBe('');
    });

    it('refuses a Core module that would depend on a higher tier', () => {
      // hrm is the enterprise module in the tree. A Core module reaching up into it would
      // make the foundation depend on the product sitting on it.
      expect(refuse({ tier: 'core', dependsOn: ['hrm'] })).toMatch(
        /core tier.*'hrm'.*enterprise tier/is,
      );
      // The other direction is fine, which is the half of the rule worth proving too.
      expect(refuse({ tier: 'custom', dependsOn: ['hrm'] })).toBe('');
    });

    it('refuses a dependency that is not there, and a name that could not be a directory', () => {
      expect(refuse({ dependsOn: ['accounting'] })).toMatch(/not present/i);
      expect(refuse({ name: 'Widgets' })).toMatch(/lowercase kebab-case/i);
      expect(refuse({ name: 'stock', record: 'parties' })).toMatch(/not a model name/i);
    });

    it('refuses a record another module already owns', () => {
      // Every table has exactly one owner, which is what "a module may not query another
      // module's tables" is checked against.
      expect(refuse({ name: 'directory', record: 'Party' })).toMatch(/parties.*already owns/is);
    });
  });

  /**
   * The criterion, asked of the two functions the build itself asks.
   *
   * `assembleModules` is what the application runs at boot and what `check:modules` runs in
   * CI; `checkConformance` is what `check:conformance` runs. Neither is a re-implementation
   * for the test's benefit — they are the same code, handed a module that does not exist yet.
   */
  describe('a freshly generated module, put through the build', () => {
    const existing = discoverManifests();
    const plan = planModule(request({ dependsOn: ['parties'] }));

    it('assembles into the application beside every module already there', () => {
      const assembled = assembleModules([...existing, asManifest(plan)]);

      expect(assembled.manifests.map((manifest) => manifest.name)).toContain('widgets');
      // After what it depends on, which is what makes the migration order real: Prisma
      // applies migrations in name order and knows nothing about modules.
      expect(assembled.migrations).toEqual([...assembled.migrations].sort());
      expect(assembled.modelOwners.Widget).toBe('widgets');
      expect(assembled.navigation.map((entry) => entry.module)).toContain('widgets');
    });

    it('passes every rule in the conformance pack', () => {
      const violations = checkConformance({
        modules: [...existing, asManifest(plan)],
        sources: [...readSources(), ...plan.files.filter(isSource)],
        modelOwners: assembleModules([...existing, asManifest(plan)]).modelOwners,
        // The classification the generator patches in, which the pack would otherwise — and
        // correctly — refuse the module for lacking.
        classifiedModels: [...classifiedModels(), 'Widget'],
        grantsByModel: grantsByModel(),
      });

      expect(violations.map((violation) => `${violation.path}: ${violation.message}`)).toEqual([]);
    });

    it('is refused by the same assembly if the graph it declares cannot boot', () => {
      // The test above passes because the module is right, not because the check is asleep.
      const impossible = { ...asManifest(plan), dependsOn: ['accounting'] };
      expect(() => assembleModules([...existing, impossible])).toThrow(ModuleContractError);
    });
  });

  describe('writing it out', () => {
    let root: string;

    beforeEach(() => {
      root = mkdtempSync(join(tmpdir(), 'erp-generator-'));
      // The three files the patches need. Their real contents are asserted against above;
      // what matters here is that the writer finds them, edits them, and edits nothing else.
      write(root, 'backend/prisma/schema.prisma', '// schema\n');
      write(
        root,
        'backend/src/platform/tenancy/company-owned.ts',
        'const CLASSIFICATION = {\n  Party: { kind: 1 },\n};\n',
      );
      write(root, 'packages/src/index.ts', "export * from './http/error.js';\n");
    });

    afterEach(() => {
      rmSync(root, { recursive: true, force: true });
    });

    it('writes every file and applies every patch', () => {
      const plan = planModule(request());
      const written = writeModule(plan, root);

      expect(written).toHaveLength(plan.files.length + plan.patches.length);
      for (const file of plan.files) {
        expect(readFileSync(join(root, file.path), 'utf8')).toBe(file.text);
      }
      expect(readFileSync(join(root, 'packages/src/index.ts'), 'utf8')).toContain('widgets');
    });

    it('writes nothing at all when a target is already there', () => {
      const plan = planModule(request());
      write(root, 'backend/src/modules/widgets/index.ts', 'mine\n');

      expect(() => writeModule(plan, root)).toThrow(/would overwrite/i);
      // Half a generated module is worse than none: the person who asked for it would have to
      // know which files to delete and which central file to revert, and they have no list.
      expect(readFileSync(join(root, 'packages/src/index.ts'), 'utf8')).not.toContain('widgets');
      expect(readFileSync(join(root, 'backend/src/modules/widgets/index.ts'), 'utf8')).toBe('mine\n');
    });
  });
});

/** The sources the conformance pack reads: TypeScript, in the workspaces it looks at. */
function isSource(file: { path: string }): boolean {
  return /\.tsx?$/.test(file.path) && !file.path.startsWith('backend/test/');
}

function write(root: string, path: string, text: string): void {
  const full = join(root, path);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, text, 'utf8');
}
