import type { ModuleTier } from '@erp/shared';
import type { ModuleNames } from './module-name';

/**
 * What a new module is on the day it is created.
 *
 * Not a skeleton with `TODO` in it. A generated module has a table, an endpoint that lists it
 * under the platform's conventions, a form that creates a row, a screen that shows the empty
 * state a fresh company actually sees, and tests for all of it — so `npm run check:modules`,
 * `npm run check:conformance` and both suites pass the moment it is generated, and the first
 * thing the person who asked for it does is *change* working code rather than fill in blanks.
 *
 * That is the difference between a generator and a snippet. A snippet leaves the interesting
 * decisions — how a list is paged, where the company filter goes, what an error body looks
 * like — to whoever is writing the eleventh module at four in the afternoon. Every one of
 * those decisions is already made here, and made the same way as in the three modules this
 * was extracted from.
 *
 * The templates are text rather than files copied from a real module, because a copied module
 * would carry its own domain with it and somebody would have to decide, per file, what to
 * strip. The cost is that these are not type-checked as they are written; what checks them is
 * that products was generated by them and is compiled by the build like everything else.
 */

/**
 * The frontend's entry point on the shared package, named indirectly.
 *
 * Written as a constant rather than inline in the template below, because the conformance
 * pack refuses that specifier in *any* file under `backend/` — the two entry points exist so
 * that Nest never acquires React — and it reads a file's import lines wherever they appear,
 * including inside a string holding a frontend module's source. The rule is right and this
 * file is the one legitimate exception to it, so it takes the indirection rather than the
 * rule taking an exemption: an exemption would be a hole in a rule about the whole backend,
 * and this is one word in one template.
 */
const SHARED_UI = '@erp/shared/ui';

export function manifestFile(names: ModuleNames, tier: ModuleTier, dependsOn: readonly string[], migration: string): string {
  const dependencies = dependsOn.length === 0 ? '[]' : `[${dependsOn.map(quote).join(', ')}]`;

  return `import { ${names.constant}_MODULE, ${names.constant}_ROUTE } from '@erp/shared';
import type { ModuleManifest } from '../../platform/modules';
import { ${names.pascal}Module } from './${names.name}.module';

/**
 * ${sentenceCase(names.words)}, declared.
 *
 * Everything the application knows about this module before it starts it. Read without
 * running anything, which is what lets the build refuse a bad module graph rather than a
 * deployment discovering one.
 */
export const manifest: ModuleManifest = {
  name: ${names.constant}_MODULE,

  tier: '${tier}',

  /**
   * The modules this one may reach, and the only ones it may import. Note what does *not*
   * belong here: the company comes from the platform's tenant scoping and the caller from
   * its session seam, so neither makes this module depend on identity.
   */
  dependsOn: ${dependencies},

  nestModule: ${names.pascal}Module,

  routes: [${names.constant}_ROUTE],

  migrations: ['${migration}'],

  models: ['${names.record}'],

  permissions: ['${names.name}:${names.name}:read', '${names.name}:${names.name}:write'],

  navigation: [
    {
      label: '${sentenceCase(names.words)}',
      path: '/${names.name}',
      order: 50,
      permission: '${names.name}:${names.name}:read',
    },
  ],

  /**
   * Nothing yet, and that is the right default. A declared event is a promise the assembler
   * enforces; one nobody consumes is a promise made to nobody. Declare it when something
   * listens.
   */
  events: {
    emits: [],
    consumes: [],
  },
};
`;
}

export function nestModuleFile(names: ModuleNames): string {
  return `import { Module } from '@nestjs/common';
import { ${names.pascal}Controller } from './${names.name}.controller';
import { ${names.pascal}Service } from './${names.name}.service';

/**
 * ${sentenceCase(names.words)}.
 *
 * Exports nothing. When another module needs something from this one, declare an abstract
 * class in 'index.ts', bind the service to it here with 'useExisting', and export *that* —
 * never the service, so the contract cannot be widened by accident on the far side of a
 * 'dependsOn' somebody added for a different reason. Export this module from 'index.ts' too,
 * because a consumer has to import it in order to inject what it provides.
 * 'backend/src/modules/parties' is the worked example.
 */
@Module({
  controllers: [${names.pascal}Controller],
  providers: [${names.pascal}Service],
})
export class ${names.pascal}Module {}
`;
}

export function publicSurfaceFile(names: ModuleNames): string {
  return `/**
 * ${sentenceCase(names.words)}' public surface.
 *
 * Empty, deliberately: this module offers other modules nothing yet. That is a real answer
 * rather than an omission, and it is the one identity and hrm give.
 *
 * When it does have something to offer, it is an abstract class declared here — the shape of
 * the question another module may ask — with '${names.pascal}Service' bound to it in the Nest
 * module, and '${names.pascal}Module' exported beside it, because a consumer has to import
 * the module in order to inject what it provides. Everything else in this directory stays
 * internal, including the service and the tables, so this file is the whole of what the rest
 * of the system may name.
 */
export {};
`;
}

export function controllerFile(names: ModuleNames): string {
  return `import { Body, Controller, Get, HttpCode, HttpStatus, Param, Patch, Post, Query } from '@nestjs/common';
import {
  ${names.constant}_ROUTE,
  type ${names.record}ListResponse,
  type ${names.record}Response,
} from '@erp/shared';
import { validated, type Valid } from '../../platform/validation';
import { ${names.pascal}Service } from './${names.name}.service';
import { Create${names.record}Body, Update${names.record}Body } from './schemas';

/**
 * The module's surface.
 *
 * Nothing is '@Public()', which is the default every endpoint in the system has: a global
 * guard requires a session, and opting out is explicit and rare.
 *
 * There is no 'DELETE'. A record is deactivated rather than deleted, so that anything naming
 * it later still means something — see the service.
 *
 * The list endpoint hands its whole query object to the service and names no parameter of its
 * own. 'page', 'sort', 'search' and 'filter.<field>' are the platform's convention, identical
 * in every module, and a controller with an opinion about them is a module inventing its own.
 */
@Controller(${names.constant}_ROUTE)
export class ${names.pascal}Controller {
  constructor(private readonly ${names.name.replace(/-/g, '')}: ${names.pascal}Service) {}

  @Post()
  @HttpCode(HttpStatus.CREATED)
  async add(
    @Body(validated(Create${names.record}Body)) body: Valid<typeof Create${names.record}Body>,
  ): Promise<${names.record}Response> {
    return this.${names.name.replace(/-/g, '')}.create${names.record}(body);
  }

  @Get()
  async list(@Query() query: Record<string, unknown>): Promise<${names.record}ListResponse> {
    return this.${names.name.replace(/-/g, '')}.list${names.record}s(query);
  }

  @Get(':id')
  async one(@Param('id') id: string): Promise<${names.record}Response> {
    return this.${names.name.replace(/-/g, '')}.${names.delegate}Detail(id);
  }

  @Patch(':id')
  async change(
    @Param('id') id: string,
    @Body(validated(Update${names.record}Body)) body: Valid<typeof Update${names.record}Body>,
  ): Promise<${names.record}Response> {
    return this.${names.name.replace(/-/g, '')}.change${names.record}(id, body);
  }
}
`;
}

export function serviceFile(names: ModuleNames): string {
  const field = names.name.replace(/-/g, '');

  return `import { HttpStatus, Injectable } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import {
  ${names.recordConstant}_ERROR_CODES,
  type ${names.record}ListResponse,
  type ${names.record}Response,
  type ${names.record}Status,
  type ${names.record}Summary,
} from '@erp/shared';
import { ApiException } from '../../http/api-exception';
import { listQuery } from '../../platform/list';
import { companyApplied, InjectPrisma, type ScopedPrisma } from '../../platform/tenancy';
import type { Valid } from '../../platform/validation';
import { defined } from '../../prisma/columns';
import { Create${names.record}Body, ${names.recordConstant}_LIST, Update${names.record}Body } from './schemas';

/**
 * What ${names.words} actually does.
 *
 * Two things in here are the platform's rather than this module's, and both look like
 * omissions until you know why:
 *
 * - **There is no company filter anywhere.** Scoping is applied to every query below by the
 *   tenancy extension, so another company's rows are not reachable from this file even by
 *   trying. A module that wrote the filter would be a module that could forget it.
 * - **Nothing is deleted.** Deactivating keeps whatever refers to a record intelligible; a
 *   delete would leave it naming an identifier that resolves to nothing.
 */
@Injectable()
export class ${names.pascal}Service {
  constructor(@InjectPrisma() private readonly prisma: ScopedPrisma) {}

  async create${names.record}(
    input: Valid<typeof Create${names.record}Body>,
  ): Promise<${names.record}Response> {
    const ${field} = await this.prisma.${names.delegate}.create({
      data: companyApplied<Prisma.${names.record}UncheckedCreateInput>({ name: input.name }),
    });

    return describe(${field});
  }

  async list${names.record}s(query: Record<string, unknown>): Promise<${names.record}ListResponse> {
    const slice = listQuery(query, ${names.recordConstant}_LIST);

    const [rows, total] = await Promise.all([
      this.prisma.${names.delegate}.findMany(slice.findMany<Prisma.${names.record}FindManyArgs>()),
      this.prisma.${names.delegate}.count(slice.count<Prisma.${names.record}CountArgs>()),
    ]);

    return slice.respond(rows.map(describe), total);
  }

  async ${names.delegate}Detail(id: string): Promise<${names.record}Response> {
    const ${field} = await this.prisma.${names.delegate}.findFirst({ where: { id } });
    if (!${field}) throw notFound();

    return describe(${field});
  }

  /**
   * Changes a record, or deactivates it.
   *
   * Deactivation is a status rather than an endpoint of its own, because it is the same act
   * as any other correction from the caller's point of view and the same write from the
   * database's.
   */
  async change${names.record}(
    id: string,
    input: Valid<typeof Update${names.record}Body>,
  ): Promise<${names.record}Response> {
    await this.${names.delegate}Detail(id);

    const ${field} = await this.prisma.${names.delegate}.update({
      where: { id },
      data: { ...defined('name', input.name), ...defined('status', input.status) },
    });

    return describe(${field});
  }
}

function describe(row: { id: string; name: string; status: string }): ${names.record}Summary {
  return {
    id: row.id,
    name: row.name,
    // The column is text rather than a Postgres enum, so the wire type is asserted here, at
    // the one boundary where the two representations meet.
    status: row.status as ${names.record}Status,
  };
}

/**
 * The same 404 a record in another company gets, deliberately. Telling a caller that an
 * identifier is real but not theirs would turn the endpoint into a way of counting somebody
 * else's rows.
 */
function notFound(): ApiException {
  return new ApiException(
    ${names.recordConstant}_ERROR_CODES.${names.delegate}NotFound,
    'That ${names.recordWords} does not exist.',
    HttpStatus.NOT_FOUND,
  );
}
`;
}

export function schemasFile(names: ModuleNames): string {
  return `import { ${names.recordConstant}_FIELDS, ${names.recordConstant}_STATUSES, type ${names.record}Status } from '@erp/shared';
import type { ListSpec } from '../../platform/list';
import { oneOf, optional, text, validator } from '../../platform/validation';

/**
 * What this module accepts, and what it lets a caller ask of its list.
 *
 * Declared beside the module rather than in the platform, because the wording is the part
 * that belongs to whoever owns the screen: "Enter a name." and "Enter the ${names.recordWords}'s
 * name." are the same rule and different sentences.
 */

const ${names.recordConstant}_NAME = {
  missing: 'Enter a name.',
  maxLength: 200,
  tooLong: 'Use 200 characters or fewer.',
} as const;

const STATUS = oneOf<${names.record}Status>(${names.recordConstant}_STATUSES, {
  missing: 'Say whether this ${names.recordWords} is active.',
  invalid: 'That is not a status you can set.',
});

export const Create${names.record}Body = validator({
  name: text(${names.recordConstant}_NAME),
});

/** A change. Every field optional, at least one required — absent means "do not touch it". */
export const Update${names.record}Body = validator({
  name: optional(text(${names.recordConstant}_NAME)),
  status: optional(STATUS),
}).and((values, report) => {
  const changed = Object.values(values).some((value) => value !== undefined);
  if (!changed) report('name', 'Change something — this request changes nothing.');
});

/**
 * What a caller may do to the list.
 *
 * An allow-list: a field nobody names here is not reachable from a query string at all, so
 * '?sort=somethingPrivate' is refused before anything touches the database.
 */
export const ${names.recordConstant}_LIST: ListSpec = {
  defaultSort: ${names.recordConstant}_FIELDS.name,
  fields: {
    [${names.recordConstant}_FIELDS.name]: { type: 'text', sortable: true, filterable: true, searchable: true },
    [${names.recordConstant}_FIELDS.status]: { type: 'text', sortable: true, filterable: true },
    [${names.recordConstant}_FIELDS.createdAt]: { type: 'date', sortable: true, filterable: true },
  },
};
`;
}

export function contractFile(names: ModuleNames): string {
  return `import type { ListResponse } from '../../http/list.js';

/**
 * ${sentenceCase(names.words)}' wire contract — its paths, bodies, responses and refusals.
 *
 * Wire shapes only, as with every contract here. What a ${names.recordWords} *is* lives in
 * 'backend/src/modules/${names.name}', and what other modules may ask of it is that module's
 * public surface. Nothing outside the module reads its tables.
 *
 * Both workspaces bind to this file, so an API change breaks the build rather than the user's
 * screen.
 */

export const ${names.constant}_MODULE = '${names.name}';

/** No leading slash — Nest composes controller prefixes. */
export const ${names.constant}_ROUTE = 'api/${names.name}';

export const ${names.recordConstant}_PATHS = {
  ${camel(names.name)}: \`/\${${names.constant}_ROUTE}\`,
  ${names.delegate}: (id: string) => \`/\${${names.constant}_ROUTE}/\${id}\`,
} as const;

/**
 * Active, or kept for the sake of history.
 *
 * 'inactive' is what deactivation produces — something nobody uses any more, whose past still
 * has to make sense. Nothing here is ever deleted.
 */
export const ${names.recordConstant}_STATUSES = ['active', 'inactive'] as const;

export type ${names.record}Status = (typeof ${names.recordConstant}_STATUSES)[number];

/**
 * The fields a caller may sort, filter or search the list by.
 *
 * Named here rather than as string literals on either side: the backend's list declaration
 * and the frontend's table columns have to agree, so a rename should be a type error in both
 * workspaces rather than a list that quietly stops sorting.
 */
export const ${names.recordConstant}_FIELDS = {
  name: 'name',
  status: 'status',
  createdAt: 'createdAt',
} as const;

export interface Create${names.record}Request {
  name: string;
}

export interface Update${names.record}Request {
  name?: string;
  status?: ${names.record}Status;
}

export interface ${names.record}Summary {
  id: string;
  name: string;
  status: ${names.record}Status;
}

export type ${names.record}Response = ${names.record}Summary;

export type ${names.record}ListResponse = ListResponse<${names.record}Summary>;

export const ${names.recordConstant}_ERROR_CODES = {
  ${names.delegate}NotFound: '${names.table}_not_found',
} as const;
`;
}

export function frontendManifestFile(names: ModuleNames): string {
  return `import { ${names.constant}_MODULE } from '@erp/shared';
import type { FrontendModuleManifest } from '../../app/module-manifest';
import { ${names.pascal}Page } from './pages/${names.pascal}Page';

/**
 * Which component renders which path — the one thing the server cannot decide.
 *
 * Found by the registry because this file exists at this path; no route table anywhere lists
 * it. The path matches the navigation entry the backend manifest declares, which is how a
 * menu entry finds a screen.
 */
export const manifest: FrontendModuleManifest = {
  name: ${names.constant}_MODULE,
  routes: [{ path: '/${names.name}', component: ${names.pascal}Page }],
};
`;
}

export function pageFile(names: ModuleNames): string {
  return `import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { ColumnDef } from '@tanstack/react-table';
import {
  ERROR_CODES,
  ${names.recordConstant}_FIELDS,
  ${names.recordConstant}_PATHS,
  emptyPage,
  listPath,
  listQueryString,
  type Create${names.record}Request,
  type ListQuery,
  type ${names.record}ListResponse,
  type ${names.record}Response,
  type ${names.record}Status,
  type ${names.record}Summary,
} from '@erp/shared';
import { DataTable, Field, FormError } from '${SHARED_UI}';
import { ApiFailure, api } from '../../../api/client';

/**
 * ${sentenceCase(names.words)}.
 *
 * Everything about paging, sorting, filtering and searching is the platform's: this holds a
 * 'ListQuery' in state, hands it to the shared table, and builds the URL with the shared
 * helper. What a screen contributes is the columns, the filter controls its own fields
 * deserve, and the form.
 */
export function ${names.pascal}Page() {
  const [query, setQuery] = useState<ListQuery>({});
  const queryClient = useQueryClient();

  const ${camel(names.name)} = useQuery({
    // The query string *is* the cache key: two different requests are two different answers,
    // and the shared builder sorts its parameters so one request is always one key.
    queryKey: ['${names.name}', 'list', listQueryString(query)],
    queryFn: () =>
      api.get<${names.record}ListResponse>(listPath(${names.recordConstant}_PATHS.${camel(names.name)}, query)),
  });

  const failure = ${camel(names.name)}.error instanceof ApiFailure ? ${camel(names.name)}.error : undefined;

  const columns = useMemo<Array<ColumnDef<${names.record}Summary, unknown>>>(
    () => [
      // The id is the field name the server sorts by, taken from the shared contract so a
      // rename breaks the build rather than the sort.
      { id: ${names.recordConstant}_FIELDS.name, header: 'Name', cell: ({ row }) => row.original.name },
      {
        id: ${names.recordConstant}_FIELDS.status,
        header: 'Status',
        cell: ({ row }) => STATUS_LABELS[row.original.status],
      },
    ],
    [],
  );

  return (
    <div className="flex flex-col gap-8">
      <header className="flex flex-col gap-1">
        <h1 className="text-2xl font-semibold text-slate-900">${sentenceCase(names.words)}</h1>
        <p className="text-sm text-slate-600">Everything this company keeps here.</p>
      </header>

      <Add${names.record}
        onAdded={() => {
          // The list is stale the moment a row is added, and a screen showing a list that
          // does not contain what you just created is a screen nobody trusts again.
          void queryClient.invalidateQueries({ queryKey: ['${names.name}'] });
          setQuery({});
        }}
      />

      <DataTable
        caption="${sentenceCase(names.words)}"
        columns={columns}
        rows={${camel(names.name)}.data?.items ?? []}
        rowId={(row) => row.id}
        page={${camel(names.name)}.data?.page ?? emptyPage()}
        query={query}
        onQueryChange={setQuery}
        status={${camel(names.name)}.isPending ? 'loading' : ${camel(names.name)}.isError ? 'error' : 'ready'}
        error={failure?.message}
        onRetry={() => void ${camel(names.name)}.refetch()}
        searchLabel="Search by name"
        empty={
          <div className="flex flex-col gap-1">
            <p className="font-medium text-slate-900">Nothing here yet.</p>
            <p>Add your first ${names.recordWords} using the form above.</p>
          </div>
        }
      />
    </div>
  );
}

const STATUS_LABELS = {
  active: 'Active',
  inactive: 'Inactive',
} as const satisfies Record<${names.record}Status, string>;

/**
 * The form that creates one.
 *
 * On the page rather than behind a button, because of the empty state it has to serve:
 * nothing in this system is seeded, so an empty list is the first thing every user sees and
 * the thing the screen should guide them towards is right there.
 */
function Add${names.record}({ onAdded }: { onAdded: (created: ${names.record}Response) => void }) {
  const [name, setName] = useState('');

  const add = useMutation({
    mutationFn: () =>
      api.post<${names.record}Response>(${names.recordConstant}_PATHS.${camel(names.name)}, {
        name,
      } satisfies Create${names.record}Request),
    onSuccess: (created) => {
      setName('');
      onAdded(created);
    },
  });

  const failure = add.error instanceof ApiFailure ? add.error : undefined;
  const fields = failure?.fields ?? {};

  return (
    <form
      noValidate
      aria-labelledby="add-${names.name}"
      className="flex flex-col gap-4 rounded-md border border-slate-200 bg-white p-4"
      onSubmit={(event) => {
        event.preventDefault();
        add.mutate();
      }}
    >
      <h2 id="add-${names.name}" className="text-sm font-medium text-slate-900">
        Add a ${names.recordWords}
      </h2>

      <div className="flex flex-wrap gap-4">
        <div className="min-w-56 flex-1">
          <Field id="${names.name}-name" label="Name" value={name} error={fields.name} onChange={setName} />
        </div>
      </div>

      {failure && failure.code !== ERROR_CODES.validationFailed && (
        <FormError>{failure.message}</FormError>
      )}

      <div>
        <button
          type="submit"
          disabled={add.isPending}
          className="rounded-md bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700 disabled:opacity-50"
        >
          {add.isPending ? 'Adding…' : 'Add ${names.recordWords}'}
        </button>
      </div>
    </form>
  );
}
`;
}

export function pageTestFile(names: ModuleNames): string {
  return `import { describe, expect, it } from 'vitest';
import { screen, waitFor } from '@testing-library/react';
import { http, HttpResponse } from 'msw';
import { ${names.recordConstant}_PATHS, type ${names.record}ListResponse, type ${names.record}Summary } from '@erp/shared';
import { server } from '../../../test/server';
import { renderPage } from '../../../test/render';
import { ${names.pascal}Page } from './${names.pascal}Page';

/**
 * The screen from the user's side.
 *
 * Requests are intercepted at the network boundary and their query strings captured, because
 * "sorted" and "filtered" are only true if the *server* was asked: a screen that reordered
 * rows it was already holding would pass a weaker test and be wrong on page two.
 */
describe('${names.pascal}Page', () => {
  const PAGE_SIZE = 25;

  function row(name: string, overrides: Partial<${names.record}Summary> = {}): ${names.record}Summary {
    return { id: \`id-\${name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}\`, name, status: 'active', ...overrides };
  }

  function page(items: ${names.record}Summary[], total = items.length): ${names.record}ListResponse {
    return { items, page: { number: 1, size: PAGE_SIZE, total, pages: Math.ceil(total / PAGE_SIZE) } };
  }

  function listing(respond: (parameters: URLSearchParams) => ${names.record}ListResponse): { asked: string[] } {
    const asked: string[] = [];

    server.use(
      http.get(${names.recordConstant}_PATHS.${camel(names.name)}, ({ request }) => {
        const url = new URL(request.url);
        asked.push(url.search);
        return HttpResponse.json(respond(url.searchParams));
      }),
    );

    return { asked };
  }

  it('shows what is there', async () => {
    listing(() => page([row('First'), row('Second', { status: 'inactive' })]));

    renderPage(<${names.pascal}Page />, { path: '/${names.name}' });

    expect(await screen.findByText('First')).toBeInTheDocument();
    expect(screen.getByText('Inactive')).toBeInTheDocument();
  });

  it('guides the first action rather than showing an empty box', async () => {
    listing(() => page([]));

    renderPage(<${names.pascal}Page />, { path: '/${names.name}' });

    // Nothing is seeded in this system, so this is the first thing a real user sees.
    expect(await screen.findByText(/nothing here yet/i)).toBeInTheDocument();
  });

  it('asks the server to sort when a column heading is clicked', async () => {
    const { asked } = listing(() => page([row('First')]));

    const { user } = renderPage(<${names.pascal}Page />, { path: '/${names.name}' });
    await screen.findByText('First');

    await user.click(screen.getByRole('button', { name: /^name$/i }));
    await waitFor(() => expect(asked.at(-1)).toContain('sort=name'));
  });

  it('creates one and refreshes the list', async () => {
    let sent: unknown;
    let created = false;

    server.use(
      http.get(${names.recordConstant}_PATHS.${camel(names.name)}, () =>
        HttpResponse.json(created ? page([row('First')]) : page([])),
      ),
      http.post(${names.recordConstant}_PATHS.${camel(names.name)}, async ({ request }) => {
        sent = await request.json();
        created = true;
        return HttpResponse.json(row('First'), { status: 201 });
      }),
    );

    const { user } = renderPage(<${names.pascal}Page />, { path: '/${names.name}' });
    await screen.findByText(/nothing here yet/i);

    await user.type(screen.getByLabelText(/^name$/i), 'First');
    await user.click(screen.getByRole('button', { name: /add ${names.recordWords}/i }));

    await waitFor(() => expect(sent).toEqual({ name: 'First' }));
    expect(await screen.findByRole('cell', { name: 'First' })).toBeInTheDocument();
  });

  it('puts a server message beside the input it belongs to', async () => {
    server.use(
      http.get(${names.recordConstant}_PATHS.${camel(names.name)}, () => HttpResponse.json(page([]))),
      http.post(${names.recordConstant}_PATHS.${camel(names.name)}, () =>
        HttpResponse.json(
          {
            code: 'validation_failed',
            message: 'Some of the details you entered need attention.',
            fields: { name: 'Enter a name.' },
          },
          { status: 422 },
        ),
      ),
    );

    const { user } = renderPage(<${names.pascal}Page />, { path: '/${names.name}' });
    await screen.findByText(/nothing here yet/i);

    await user.click(screen.getByRole('button', { name: /add ${names.recordWords}/i }));

    const name = await screen.findByLabelText(/^name$/i);
    expect(name).toHaveAttribute('aria-invalid', 'true');
    expect(name).toHaveAccessibleDescription(/enter a name/i);
  });
});
`;
}

export function backendTestFile(names: ModuleNames): string {
  return `import {
  AUTH_PATHS,
  ${names.recordConstant}_PATHS,
  listPath,
  type AuthenticatedSession,
  type ${names.record}ListResponse,
  type ${names.record}Response,
  type SignUpRequest,
} from '@erp/shared';
import { createTestApp, resetDatabase, type TestApp } from './harness/test-app';

/**
 * ${sentenceCase(names.words)}, over HTTP, against a real database. Nothing is mocked and
 * nothing reaches below the endpoint.
 *
 * Two companies are signed up in the isolation test rather than one, because "a row belongs
 * to a company" is a claim you cannot make with only one company in the database: every query
 * would pass whether or not scoping worked at all.
 */
describe('${names.name}', () => {
  let app: TestApp;

  type SupertestRequest = ReturnType<TestApp['http']['get']>;

  interface Tenant {
    session: AuthenticatedSession;
    as: (request: SupertestRequest) => SupertestRequest;
  }

  beforeAll(async () => {
    app = await createTestApp();
  });

  afterAll(async () => {
    await app.close();
  });

  beforeEach(async () => {
    await resetDatabase(app);
  });

  async function signUp(overrides: Partial<SignUpRequest> = {}): Promise<Tenant> {
    const response = await app.http
      .post(AUTH_PATHS.signUp)
      .send({
        companyName: 'Northwind Trading',
        name: 'Ada Okafor',
        email: 'ada@northwind.test',
        password: 'correct-horse-battery',
        ...overrides,
      })
      .expect(201);

    const session = response.body as AuthenticatedSession;
    return { session, as: (request) => request.set('Authorization', \`Bearer \${session.token}\`) };
  }

  async function add(tenant: Tenant, name: string): Promise<${names.record}Response> {
    const response = await tenant
      .as(app.http.post(${names.recordConstant}_PATHS.${camel(names.name)}))
      .send({ name })
      .expect(201);

    return response.body as ${names.record}Response;
  }

  it('records one, and lists it in the envelope every list endpoint returns', async () => {
    const tenant = await signUp();
    await add(tenant, 'First');

    const response = await tenant
      .as(app.http.get(listPath(${names.recordConstant}_PATHS.${camel(names.name)}, { pageSize: 10 })))
      .expect(200);

    const listed = response.body as ${names.record}ListResponse;
    expect(listed.items.map((item) => item.name)).toEqual(['First']);
    expect(listed.page).toEqual({ number: 1, size: 10, total: 1, pages: 1 });
  });

  it('says what is wrong with the input rather than failing obscurely', async () => {
    const tenant = await signUp();

    const refused = await tenant
      .as(app.http.post(${names.recordConstant}_PATHS.${camel(names.name)}))
      .send({ name: '' })
      .expect(422);

    expect(refused.body.fields).toHaveProperty('name');
  });

  it('deactivates rather than deleting, and keeps the record', async () => {
    const tenant = await signUp();
    const created = await add(tenant, 'First');

    const changed = await tenant
      .as(app.http.patch(${names.recordConstant}_PATHS.${names.delegate}(created.id)))
      .send({ status: 'inactive' })
      .expect(200);

    expect((changed.body as ${names.record}Response).status).toBe('inactive');
    // Still there, still findable by its identifier — which is what makes anything naming it
    // later intelligible.
    await tenant.as(app.http.get(${names.recordConstant}_PATHS.${names.delegate}(created.id))).expect(200);
    await tenant.as(app.http.delete(${names.recordConstant}_PATHS.${names.delegate}(created.id))).expect(404);
  });

  it('is not a filter any of this code writes, and one company cannot see another', async () => {
    const northwind = await signUp();
    const acme = await signUp({ companyName: 'Acme', name: 'Bo Lindqvist', email: 'bo@acme.test' });

    const theirs = await add(northwind, 'Theirs');
    await add(acme, 'Ours');

    const listed = await acme.as(app.http.get(${names.recordConstant}_PATHS.${camel(names.name)})).expect(200);
    expect((listed.body as ${names.record}ListResponse).items.map((item) => item.name)).toEqual(['Ours']);

    // By its own identifier, which is the case a list filter would not cover: the id is real,
    // and the answer is the one a made-up id gets.
    await acme.as(app.http.get(${names.recordConstant}_PATHS.${names.delegate}(theirs.id))).expect(404);
  });
});
`;
}

export function migrationFile(names: ModuleNames): string {
  return `-- CreateTable
CREATE TABLE "${names.table}" (
    "id" UUID NOT NULL,
    "company_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "${names.table}_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "${names.table}_company_id_idx" ON "${names.table}"("company_id");

-- CreateIndex
CREATE INDEX "${names.table}_company_id_name_idx" ON "${names.table}"("company_id", "name");
`;
}

export function schemaSection(names: ModuleNames): string {
  return `
// ─── ${names.name} ${'─'.repeat(Math.max(0, 78 - names.name.length))}
// Owned by the ${names.name} module. See backend/src/modules/${names.name}.
//
// As everywhere else, \`companyId\` is a plain column with no foreign key to \`companies\`:
// keys stay inside a module, and scoping is the tenancy extension's rather than the schema's.

/// The module's primary record.
model ${names.record} {
  id        String @id @default(uuid()) @db.Uuid
  companyId String @map("company_id") @db.Uuid

  name String

  /// \`active\` or \`inactive\`. Deactivating rather than deleting is what keeps whatever names
  /// this row later intelligible.
  status String @default("active")

  createdAt DateTime @default(now()) @map("created_at")
  updatedAt DateTime @updatedAt @map("updated_at")

  @@index([companyId])
  /// The list's default order, within a company — the \`(company_id, <default sort>)\` shape
  /// every list endpoint's default sort wants, so that offset paging is an index walk.
  @@index([companyId, name])
  @@map("${names.table}")
}
`;
}

/**
 * The classification, as it is inserted at the end of the table in `company-owned.ts`.
 *
 * Company-owned, because that is the ordinary case and a generated module that guessed
 * `unscoped` would be a generated leak. If it is genuinely not — a table like `Session`,
 * which establishes the company and so cannot belong to one — change it to
 * `{ kind: 'unscoped', why: '…' }` and write the sentence. Somebody has to say, and the
 * application refuses to boot until they have.
 */
export function tenancyClassification(names: ModuleNames): string {
  return `

  // ─── ${names.name} ──
  ${names.record}: { kind: 'company-owned' },`;
}

export function sharedBarrelExport(names: ModuleNames): string {
  return `export * from './modules/${names.name}/contract.js';\n`;
}

function quote(value: string): string {
  return `'${value}'`;
}

function camel(name: string): string {
  const [first = '', ...rest] = name.split('-');
  return first + rest.map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join('');
}

function sentenceCase(words: string): string {
  return words.charAt(0).toUpperCase() + words.slice(1);
}
