import { PRODUCTS_MODULE, PRODUCTS_ROUTE, UNITS_ROUTE } from '@erp/shared';
import type { ModuleManifest } from '../../platform/modules';
import { ProductsModule } from './products.module';

/**
 * The product master, declared.
 *
 * Generated by `npm run new:module -- --name products --tier core --depends-on parties`, and
 * then filled in. Everything structural here — the shape of the manifest, the permission
 * namespace, the navigation entry, the migration that came with it — is what the generator
 * wrote; what was added is the domain.
 */
export const manifest: ModuleManifest = {
  name: PRODUCTS_MODULE,

  /**
   * Core, and beneath inventory rather than inside it.
   *
   * Sales, Purchase, Manufacturing and E-commerce all need to name the thing they are
   * dealing in. If products lived inside inventory, every one of them would depend on stock
   * movements and locations in order to do it — and a module in a tier above them could not
   * be depended on by the ones below in any case.
   */
  tier: 'core',

  /**
   * Parties, and only parties.
   *
   * A product is bought from somebody, and that somebody is a row in the one address book
   * rather than a supplier table of this module's own. That is the whole argument for parties
   * being a Core module, taken up by the first module in a position to take it up: the
   * reference is resolved through `PartyDirectory`, and nothing here reads a parties table or
   * knows that a party has roles.
   *
   * Not identity, which looks missing and is not: the company is applied by the platform's
   * tenant scoping and the caller arrives through its session seam. Both are the platform's,
   * and the platform is not a module.
   */
  dependsOn: ['parties'],

  nestModule: ProductsModule,

  /**
   * Two, because units are not a detail of a product. A unit exists before any product uses
   * one, is created on a screen of its own, and is what a stock movement will be measured in.
   */
  routes: [PRODUCTS_ROUTE, UNITS_ROUTE],

  /**
   * Two migrations, in the order they were written: the one the generator produced with the
   * module, and the one that turned its single table into a catalogue. Both are the module's,
   * and both sort after parties', which is what makes the dependency real to Prisma — it
   * applies migrations in name order and knows nothing about modules.
   */
  migrations: ['20260803065833_products', '20260803073335_products_catalogue'],

  models: ['UnitGroup', 'UnitOfMeasure', 'Product', 'ProductSupplier'],

  /**
   * Products and units are separate permissions because they are separate jobs. Somebody
   * correcting a SKU all day should not thereby be able to redefine what a kilogram is —
   * a ratio is a definition every quantity in the system is measured against, and changing
   * one silently re-states every stock figure derived from it.
   */
  permissions: [
    'products:products:read',
    'products:products:write',
    'products:units:read',
    'products:units:write',
  ],

  navigation: [
    { label: 'Products', path: '/products', order: 20, permission: 'products:products:read' },
    { label: 'Units', path: '/units', order: 21, permission: 'products:units:read' },
  ],

  /**
   * Nothing yet, deliberately. `products.product.created` is the obvious candidate, but a
   * declared event is a promise the assembler enforces and one nobody consumes is a promise
   * made to nobody. Inventory, in ticket 08, is the first module that could listen — and it
   * will reach for `ProductCatalogue` rather than an event, because what it needs is an
   * answer rather than a notification.
   */
  events: {
    emits: [],
    consumes: [],
  },
};
